name: Test Samples

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron:  '0 0 * * *'

jobs:
    test_samples:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                source: 
                    - m3_vedirect_service_example.yaml
                    - m3_vedirect_minimal_example.yaml
                    - m3_vedirect_flavor_ALL_example.yaml
                platform: 
                  - esp32
                  - esp32-arduino
                  - esp8266        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'

            - name: Install ESPhome
              run: |
                python -m pip install --upgrade pip
                pip install esphome

            - name: Compile
              run: |
                esphome -q -s platform ${{matrix.platform}} compile "./docs/samples/${{matrix.source}}"
